[DP-2]
path = "/home/sheldon/Pictures/walls/wallhaven-gwweme.png"
#duration = "5m"
#sorting = "random"

[DP-4]
path = "/home/sheldon/Pictures/walls/wallhaven-gwweme.png"
#duration = "5m"
#sorting = "random"
